
ChessArenas:
  arena1

Message:
  CopyFEN: "Copy FEN"
  Request:
    Accept: "&a[Accept]"
    Cancel: "&c[Cancel]"
    Draw:
      Sent: "&eYour opponent wants a draw."
      Cancelled: "&eYour opponent no longer wants a draw."
      Accepted: "&aDraw offer accepted."
    Takeback:
      Sent: "&eYour opponent wants a takeback."
      Cancelled: "&eYour opponent no longer wants a takeback."
      Accepted: "&aTakeback request accepted."
  Error:
    NotPlayer: "&cYou are not a player!"
    WrongArgumentsNumber: "&cWrong number of arguments!"
    WrongArgument: "&cWrong argument!"
    NoPermission: "&cYou do not have permission to do this!"
    PlayerNotFound: "&cPlayer doesn't exist!"
    NoArenas: "&cThere are no free arenas!"
    EngineNotFound: "&cThere are no engines in this game!"
    BoardNotFound: "&cYour game has no chessboard!"
    ClockNotFound: "&cYour game has no clock!"
    NothingToTakeback: "&cThere are no moves to takeback!"
    HasTurn:
      You: "&cIt is your turn!"
      Opponent: "&cIt is your opponent's turn!"
    NotHuman:
      Opponent: "&cYour opponent is not a human!"
    InGame:
      You: "&cYou are already in a game!"
      Opponent: "&cYour opponent is in a game already!"
    NotInGame:
      You: "&cYou are not in a game!"
      Player: "&cThe player isn't in a game!"
