
ChessArenas:
  arena1

Message:
  CopyFEN: "Copy FEN"
  ChooseSettings: "Choose settings"
  YourTurn: "&eIt is your turn"
  YouArePlayingAs:
    White: "&eYou are playing with the white pieces"
    Black: "&eYou are playing with the black pieces"
  YouWon: "&aYou won"
  YouLost: "&cYou lost"
  YouDrew: "&eYou drew"
  WhiteWon: "&eWhite won"
  BlackWon: "&eBlack won"
  ItWasADraw: "&eDraw"
  Request:
    Accept: "&a[Accept]"
    Cancel: "&c[Cancel]"
    Duel:
      Sent:
        Request: "&eDuel request sent."
        Cancel: "&eYou cancelled the duel with $1."
        Accept: "&aYou accepted the duel request."
      Received:
        Request: "&e$1 challenges you to a chess game: $2."
        Cancel: "&eDuel with $1 has been cancelled."
        Accept: "&aYour duel request has been accepted."
      NotFound: "&cDuel request not found."
      AlreadySent: "&cDuel request already sent."
    Draw:
      Sent:
        Request: "&eDraw offer sent."
        Cancel: "&eYou cancelled the draw offer."
        Accept: "&aYou accepted the draw offer."
      Received:
        Request: "&eYour opponent wants a draw."
        Cancel: "&eThe draw offer has been cancelled."
        Accept: "&aThe draw offer has been accepted."
      CannotSend: "&cIt is your opponent's turn!"
    Takeback:
      Sent:
        Request: "&eTakeback request sent."
        Cancel: "&eYou cancelled the takeback request."
        Accept: "&aYou accepted the takeback request."
      Received:
        Request: "&eYour opponent wants a takeback."
        Cancel: "&eThe takeback request has been cancelled."
        Accept: "&aThe takeback request has been accepted."
      CannotSend: "&cIt is your turn!"
  Error:
    NotPlayer: "&cYou are not a player!"
    WrongArgumentsNumber: "&cWrong number of arguments!"
    WrongArgument: "&cWrong argument!"
    NoPermission: "&cYou do not have permission to do this!"
    PlayerNotFound: "&cPlayer doesn't exist!"
    NoArenas: "&cThere are no free arenas!"
    EngineNotFound: "&cThere are no engines in this game!"
    BoardNotFound: "&cYour game has no chessboard!"
    ClockNotFound: "&cYour game has no clock!"
    NothingToTakeback: "&cThere are no moves to takeback!"
    WrongDurationFormat: "&cWrong duration format!"
    NotHuman:
      Opponent: "&cYour opponent is not a human!"
    InGame:
      You: "&cYou are already in a game!"
      Opponent: "&cYour opponent is in a game already!"
    NotInGame:
      You: "&cYou are not in a game!"
      Player: "&cThe player isn't in a game!"
Component:
  Scoreboard:
    Title: "GregChess game"
    Preset: "Preset"
    Player: "player"
    PlayerPrefix: "&b"
    GeneralFormat: "%s:"
    WhiteFormat: "White %s:"
    BlackFormat: "Black %s:"
  Clock:
    TimeRemainingSimple: "Time remaining"
    TimeRemaining: "time"
    TimeFormat: "%02d:%02d.%d"
