
ChessArenas:
  arena1

Request:
  Accept: "&a[Accept]"
  Cancel: "&c[Cancel]"
  Duel:
    Sent:
      Request: "&eDuel request sent."
      Cancel: "&eYou cancelled the duel with $1."
      Accept: "&aYou accepted the duel request."
    Received:
      Request: "&e$1 challenges you to a chess game: $2."
      Cancel: "&eDuel with $1 has been cancelled."
      Accept: "&aYour duel request has been accepted."
    Error:
      NotFound: "&cDuel request not found."
    TimedOut: "&eDuel request with $1 has timed out."
    Duration: 5m
  Draw:
    Sent:
      Request: "&eDraw offer sent."
      Cancel: "&eYou cancelled the draw offer."
      Accept: "&aYou accepted the draw offer."
    Received:
      Request: "&eYour opponent wants a draw."
      Cancel: "&eThe draw offer has been cancelled."
      Accept: "&aThe draw offer has been accepted."
    Error:
      CannotSend: "&cIt is your opponent's turn!"
  Takeback:
    Sent:
      Request: "&eTakeback request sent."
      Cancel: "&eYou cancelled the takeback request."
      Accept: "&aYou accepted the takeback request."
    Received:
      Request: "&eYour opponent wants a takeback."
      Cancel: "&eThe takeback request has been cancelled."
      Accept: "&aThe takeback request has been accepted."
    Error:
      CannotSend: "&cIt is your turn!"
Message:
  Teleported: "&eTeleported to $1."
  CopyFEN: "Copy FEN"
  LoadedFEN: "&eLoaded FEN!"
  ChooseSettings: "Choose settings"
  PawnPromotion: "Pawn promotion"
  InCheck: "&cYou are in check!"
  ConfigReloaded: "&ePlugin config reloaded!"
  LevelSet: "&eDebug level set successfully!"
  EngineCommandSent: "&eEngine command sent!"
  TimeOpDone: "&eCompleted the chess clock operation!"
  SkippedTurn: "&eSkipped a turn!"
  BoardOpDone: "&eCompleted the chessboard operation!"
  YouArePlayingAs:
    White: "&eYou are playing with the white pieces"
    Black: "&eYou are playing with the black pieces"
  GameFinished:
    WhiteWon: "The game has finished! White won by $1."
    BlackWon: "The game has finished! Black won by $1."
    ItWasADraw: "The game has finished! It was a draw by $1."
  Error:
    NoPerms: "&cYou do not have the permission to do that!"
    NotPlayer: "&cYou are not a player!"
    WrongArgumentsNumber: "&cWrong number of arguments!"
    WrongArgument: "&cWrong argument!"
    NoPermission: "&cYou do not have permission to do this!"
    PlayerNotFound: "&cPlayer doesn't exist!"
    NoArenas: "&cThere are no free arenas!"
    GameNotFound: "&cGame not found!"
    EngineNotFound: "&cThere are no engines in this game!"
    BoardNotFound: "&cYour game has no chessboard!"
    ClockNotFound: "&cYour game has no clock!"
    NothingToTakeback: "&cThere are no moves to takeback!"
    WrongDurationFormat: "&cWrong duration format!"
    TeleportFailed: "&cTeleport failed!"
    NotHuman:
      Opponent: "&cYour opponent is not a human!"
    InGame:
      You: "&cYou are already in a game!"
      Opponent: "&cYour opponent is in a game already!"
    NotInGame:
      You: "&cYou are not in a game!"
      Player: "&cThe player isn't in a game!"

Title:
  YourTurn: "&eIt is your turn"
  InCheck: "&cYou are in check!"
  YouArePlayingAs:
    White: "&eYou are playing with the white pieces"
    Black: "&eYou are playing with the black pieces"
  Player:
    YouWon: "&aYou won"
    YouLost: "&cYou lost"
    YouDrew: "&eYou drew"
  Spectator:
    WhiteWon: "&eWhite won"
    BlackWon: "&eBlack won"
    ItWasADraw: "&eDraw"

Chess:
  Capture: "x"
  Side:
    White:
      Name: "White"
      Char: 'w'
      Piece: "&bWhite $1"
    Black:
      Name: "Black"
      Char: 'b'
      Piece: "&bBlack $1"
  Piece:
    King:
      Name: "King"
      Char: 'k'
      Item:
        White: WHITE_CONCRETE
        Black: BLACK_CONCRETE
      Structure:
        White:
          - WHITE_CONCRETE
        Black:
          - BLACK_CONCRETE
      Sound:
        PickUp: BLOCK_METAL_HIT
        Move: BLOCK_METAL_STEP
        Capture: ENTITY_ENDER_DRAGON_DEATH
    Queen:
      Name: "Queen"
      Char: 'q'
      Item:
        White: DIAMOND_BLOCK
        Black: NETHERITE_BLOCK
      Structure:
        White:
          - DIAMOND_BLOCK
        Black:
          - NETHERITE_BLOCK
      Sound:
        PickUp: ENTITY_WITCH_CELEBRATE
        Move: BLOCK_GLASS_STEP
        Capture: ENTITY_WITCH_DEATH
    Rook:
      Name: "Rook"
      Char: 'r'
      Item:
        White: IRON_BLOCK
        Black: GOLD_BLOCK
      Structure:
        White:
          - IRON_BLOCK
        Black:
          - GOLD_BLOCK
      Sound:
        PickUp: ENTITY_IRON_GOLEM_STEP
        Move: ENTITY_IRON_GOLEM_STEP
        Capture: ENTITY_IRON_GOLEM_DEATH
    Bishop:
      Name: "Bishop"
      Char: 'b'
      Item:
        White: POLISHED_DIORITE
        Black: POLISHED_BLACKSTONE
      Structure:
        White:
          - POLISHED_DIORITE
        Black:
          - POLISHED_BLACKSTONE
      Sound:
        PickUp: ENTITY_SPIDER_AMBIENT
        Move: ENTITY_SPIDER_STEP
        Capture: ENTITY_SPIDER_DEATH
    Knight:
      Name: "Knight"
      Char: 'n'
      Item:
        White: END_STONE
        Black: BLACKSTONE
      Structure:
        White:
          - END_STONE
        Black:
          - BLACKSTONE
      Sound:
        PickUp: ENTITY_HORSE_JUMP
        Move: ENTITY_HORSE_STEP
        Capture: ENTITY_HORSE_DEATH
    Pawn:
      Name: "Pawn"
      Char: 'p'
      Item:
        White: WHITE_CARPET
        Black: BLACK_CARPET
      Structure:
        White:
          - WHITE_CARPET
        Black:
          - BLACK_CARPET
      Sound:
        PickUp: BLOCK_STONE_HIT
        Move: BLOCK_STONE_STEP
        Capture: BLOCK_STONE_BREAK
  EndReason:
    Checkmate: "checkmate"
    Resignation: "resignation"
    Walkover: "walkover"
    PluginRestart: "the plugin restarting"
    ArenaRemoved: "arena deleted"
    Stalemate: "stalemate"
    InsufficientMaterial: "insufficient material"
    FiftyMoves: "the 50-move rule"
    Repetition: "repetition"
    DrawAgreement: "agreement"
    Timeout: "timeout"
    DrawTimeout: "timeout vs insufficient material"
    Error: "error"

Component:
  Scoreboard:
    Title: "GregChess game"
    Preset: "Preset"
    Player: "player"
    PlayerPrefix: "&b"
    GeneralFormat: "$1:"
    WhiteFormat: "White $1:"
    BlackFormat: "Black $1:"
  Clock:
    TimeRemainingSimple: "Time remaining"
    TimeRemaining: "time"
    TimeFormat: "mm:ss.S"
