name: GregChess
version: @version@
main: gregc.gregchess.GregChess
api-version: 1.16
author: GregC
description: Chess Plugin
commands:
  chess:
    description: Main chess command
    usage: /<command> subcommand [arguments]
    aliases: [greg-chess]
permissions:
  greg-chess.admin:
    description: Can use all /chess subcommands
    default: op
    children:
      greg-chess.debug: true
  greg-chess.debug:
    description: Can use more /chess subcommands
    default: op
    children:
      greg-chess.info: true
  greg-chess.info:
    description: Can fully use /chess info
    default: op