name: GregChess
version: @version@
main: gregc.gregchess.GregChess
api-version: 1.16
author: GregC
description: Chess Plugin
depend: [ GregCore ]
commands:
  chess:
    description: Main chess command
    usage: /<command> [duel|stockfish|resign|leave|draw|save|spectate] [player]
    aliases: [greg-chess]
permissions:
  greg-chess.debug:
    description: Can use more /chess subcommands
    default: op
