ChessArenas:

Request:
  Accept: "&a[Accept]"
  Cancel: "&c[Cancel]"
  SelfAccept: true
  Duel:
    Sent:
      Request: "&eDuel request sent."
      Cancel: "&eYou cancelled the duel request with %s."
      Accept: "&aYou accepted the duel request."
    Received:
      Request: "&e%1$s challenges you to a chess match: %2$s."
      Cancel: "&eDuel request with %s has been cancelled."
      Accept: "&aYour duel request has been accepted."
    Error:
      NotFound: "&cDuel request not found."
    Expired: "&eDuel request with %s has expired."
    Duration: 5m
  Rematch:
    Sent:
      Request: "&eRematch offer sent."
      Cancel: "&eYou cancelled the rematch offer with %s."
      Accept: "&aYou accepted the rematch offer."
    Received:
      Request: "&e%1$s offers you a rematch: %2$s."
      Cancel: "&eRematch offer with %s has been cancelled."
      Accept: "&aYour rematch offer has been accepted."
    Error:
      NotFound: "&cRematch offer not found."
    Expired: "&eRematch offer with %s has expired."
    Duration: 5m
    SendReminder: true
Message:
  Teleported: "&eTeleported to %s."
  Teleporting: "&eTeleporting..."
  CopyFEN: "Copy FEN"
  CopyPGN: "Copy PGN"
  LoadedFEN: "&eLoaded FEN!"
  ChooseSettings: "Choose settings"
  PawnPromotion: "Pawn promotion"
  InCheck: "&cYou are in check!"
  ConfigReloaded: "&ePlugin config reloaded!"
  LevelSet: "&eDebug level set successfully!"
  EngineCommandSent: "&eEngine command sent!"
  TimeOpDone: "&eCompleted the chess clock operation!"
  SkippedTurn: "&eSkipped a turn!"
  BoardOpDone: "&eCompleted the chessboard operation!"
  StatsOpDone: "&eCompleted the stats operation!"
  StatsOf: "Stats of %s"
  RejoinReminder: "&eClick to rejoin the match!"
  RematchReminder: "&eClick to send a rematch offer!"
  Draw:
    Sent:
      Request: "&eDraw offer sent."
      Cancel: "&eYou cancelled the draw offer."
      Accept: "&aYou accepted the draw offer."
    Received:
      Request: "&eYour opponent wants a draw."
      Cancel: "&eThe draw offer has been cancelled."
      Accept: "&aThe draw offer has been accepted."
    Accept: "&a[Accept]"
    Cancel: "&c[Cancel]"
  Takeback:
    Sent:
      Request: "&eTakeback request sent."
      Cancel: "&eYou cancelled the takeback request."
      Accept: "&aYou accepted the takeback request."
    Received:
      Request: "&eYour opponent wants a takeback."
      Cancel: "&eThe takeback request has been cancelled."
      Accept: "&aThe takeback request has been accepted."
    Accept: "&a[Accept]"
    Cancel: "&c[Cancel]"
  Stats:
    Wins: "&aWins: %s"
    Losses: "&cLosses: %s"
    Draws: "&eDraws: %s"
    Total: "Total"
  YouArePlayingAs:
    White: "&eYou are playing with the white pieces"
    Black: "&eYou are playing with the black pieces"
  MatchFinished:
    WhiteWon: "The match has finished! White won by %s."
    BlackWon: "The match has finished! Black won by %s."
    ItWasADraw: "The match has finished! It was a draw by %s."
  Error:
    NotPlayer: "&cYou are not a player!"
    WrongArgumentsNumber: "&cWrong number of arguments!"
    WrongArgument: "&cWrong argument!"
    InternalError: "&cAn internal error occurred!"
    NoPermission: "&cYou do not have permission to do this!"
    PlayerNotFound: "&cPlayer doesn't exist!"
    NoArenas: "&cThere are no free arenas!"
    MatchNotFound: "&cMatch not found!"
    EngineNotFound: "&cThere are no engines in this chess match!"
    ClockNotFound: "&cYour chess match has no clock!"
    PieceNotFound: "&cPiece was not found!"
    NothingToTakeback: "&cThere are no moves to takeback!"
    WrongDurationFormat: "&cWrong duration format!"
    TeleportFailed: "&cTeleport failed!"
    NoMatchToRejoin: "&cNo chess match to rejoin!"
    NoOneToRematch: "&cNo one to rematch!"
    NotYourTurn: "&cIt is your opponent's turn!"
    YourTurn: "&cIt is your turn!"
    NotHuman:
      Opponent: "&cYour opponent is not a human!"
    InMatch:
      You: "&cYou are already in a chess match!"
      Opponent: "&cYour opponent is in a chess match already!"
    NotInMatch:
      You: "&cYou are not in a chess match!"
      Player: "&cThe player isn't in a chess match!"
Title:
  YourTurn: "&eIt is your turn"
  InCheck: "&cYou are in check!"
  YouArePlayingAs:
    White: "&eYou are playing with the white pieces"
    Black: "&eYou are playing with the black pieces"
  YouArePlayingAgainst: "&eYou are playing against &c%s"
  Player:
    YouWon: "&aYou won"
    YouLost: "&cYou lost"
    YouDrew: "&eYou drew"
  Spectator:
    WhiteWon: "&eWhite won"
    BlackWon: "&eBlack won"
    ItWasADraw: "&eDraw"
Chess:
  Capture: "x"
  Check: "+"
  Checkmate: "#"
  EnPassant: " e.p."
  Color:
    White:
      Name: "White"
      Char: 'w'
      Piece: "&bWhite %s"
    Black:
      Name: "Black"
      Char: 'b'
      Piece: "&bBlack %s"
  Floor:
    Light: BIRCH_PLANKS
    Dark: SPRUCE_PLANKS
    Move: GREEN_CONCRETE
    Capture: RED_CONCRETE
    Special: BLUE_CONCRETE
    Nothing: YELLOW_CONCRETE
    Other: PURPLE_CONCRETE
    LastStart: BROWN_CONCRETE
    LastEnd: ORANGE_CONCRETE
  Piece:
    King:
      Name: "King"
      Char: 'k'
      Item:
        White: WHITE_CONCRETE
        Black: BLACK_CONCRETE
      Structure:
        White:
          - WHITE_CONCRETE
        Black:
          - BLACK_CONCRETE
      Sound:
        PickUp: BLOCK_METAL_HIT
        Move: BLOCK_METAL_STEP
        Capture: ENTITY_ENDER_DRAGON_DEATH
    Queen:
      Name: "Queen"
      Char: 'q'
      Item:
        White: DIAMOND_BLOCK
        Black: NETHERITE_BLOCK
      Structure:
        White:
          - DIAMOND_BLOCK
        Black:
          - NETHERITE_BLOCK
      Sound:
        PickUp: ENTITY_WITCH_CELEBRATE
        Move: BLOCK_GLASS_STEP
        Capture: ENTITY_WITCH_DEATH
    Rook:
      Name: "Rook"
      Char: 'r'
      Item:
        White: IRON_BLOCK
        Black: GOLD_BLOCK
      Structure:
        White:
          - IRON_BLOCK
        Black:
          - GOLD_BLOCK
      Sound:
        PickUp: ENTITY_IRON_GOLEM_STEP
        Move: ENTITY_IRON_GOLEM_STEP
        Capture: ENTITY_IRON_GOLEM_DEATH
    Bishop:
      Name: "Bishop"
      Char: 'b'
      Item:
        White: POLISHED_DIORITE
        Black: POLISHED_BLACKSTONE
      Structure:
        White:
          - POLISHED_DIORITE
        Black:
          - POLISHED_BLACKSTONE
      Sound:
        PickUp: ENTITY_SPIDER_AMBIENT
        Move: ENTITY_SPIDER_STEP
        Capture: ENTITY_SPIDER_DEATH
    Knight:
      Name: "Knight"
      Char: 'n'
      Item:
        White: END_STONE
        Black: BLACKSTONE
      Structure:
        White:
          - END_STONE
        Black:
          - BLACKSTONE
      Sound:
        PickUp: ENTITY_HORSE_JUMP
        Move: ENTITY_HORSE_STEP
        Capture: ENTITY_HORSE_DEATH
    Pawn:
      Name: "Pawn"
      Char: 'p'
      Item:
        White: WHITE_CARPET
        Black: BLACK_CARPET
      Structure:
        White:
          - WHITE_CARPET
        Black:
          - BLACK_CARPET
      Sound:
        PickUp: BLOCK_STONE_HIT
        Move: BLOCK_STONE_STEP
        Capture: BLOCK_STONE_BREAK
  HasStockfish: false
  Stockfish:
    Path: stockfish
    Name: stockfish
  EndReason:
    Checkmate: "checkmate"
    Resignation: "resignation"
    Walkover: "walkover"
    WalkoverDraw: "walkover"
    PluginDisabled: "plugin disabled"
    ArenaRemoved: "the arena getting removed"
    Stalemate: "stalemate"
    StalemateVictory: "stalemate"
    InsufficientMaterial: "insufficient material"
    FiftyMoves: "the 50-move rule"
    Repetition: "repetition"
    DrawAgreement: "agreement"
    Timeout: "timeout"
    DrawTimeout: "timeout vs insufficient material"
    Error: "error"
    CheckLimit: "check limit reached (%s)"
    KingOfTheHill: "king of the hill"
    Atomic: "explosion"
    AllPiecesLost: "all pieces lost"

Scoreboard:
  Layout: simple
  Title: "GregChess match"
  Preset: "Preset"
  Player: "player"
  PlayerPrefix: "&b"
  Format:
    General: "%s: "
    White: "White %s: "
    Black: "Black %s: "
  CheckCounter: "check counter"
  TimeRemaining: "time"
  TimeRemainingSimple: "Time remaining"

Rejoin:
  AllowRejoining: true
  SendReminder: true
  Duration: 1m

TimeFormat: "mm:ss.S"
StatsProvider: yaml
Component:
  Renderer: renderer