name: GregChess
version: @version@
main: gregc.gregchess.bukkit.GregChessPlugin$Plugin
api-version: @minecraft-version@
author: GregC
description: Chess Plugin
libraries:
@libraries@
commands:
  chess:
    description: Main chess command
    usage: /<command> subcommand [arguments]
    aliases: [gregchess]
permissions:
  gregchess.*:
    description: Can use all GregChess commands
    default: op
    children:
      gregchess.chess.*: true
  gregchess.chess.*:
    description: Can use all /chess subcommands
    default: op
    children:
      gregchess.chess.duel: true
      gregchess.chess.stockfish: true
      gregchess.chess.resign: true
      gregchess.chess.leave: true
      gregchess.chess.draw: true
      gregchess.chess.capture: true
      gregchess.chess.spawn: true
      gregchess.chess.move: true
      gregchess.chess.skip: true
      gregchess.chess.load: true
      gregchess.chess.save: true
      gregchess.chess.time: true
      gregchess.chess.uci: true
      gregchess.chess.undo: true
      gregchess.chess.spectate: true
      gregchess.chess.reload: true
      gregchess.chess.serial: true
      gregchess.chess.serialsave: true
      gregchess.chess.serialload: true
      gregchess.chess.info.*: true
      gregchess.chess.admin: true
      gregchess.chess.stats.*: true
  gregchess.chess.duel:
    description: Can use /chess duel
    default: true
  gregchess.chess.stockfish:
    description: Can use /chess stockfish
    default: true
  gregchess.chess.resign:
    description: Can use /chess resign
    default: true
  gregchess.chess.leave:
    description: Can use /chess leave
    default: true
  gregchess.chess.draw:
    description: Can use /chess draw
    default: true
  gregchess.chess.capture:
    description: Can use /chess capture
    default: op
  gregchess.chess.spawn:
    description: Can use /chess spawn
    default: op
  gregchess.chess.move:
    description: Can use /chess move
    default: op
  gregchess.chess.skip:
    description: Can use /chess skip
    default: op
  gregchess.chess.load:
    description: Can use /chess load
    default: op
  gregchess.chess.save:
    description: Can use /chess save
    default: true
  gregchess.chess.time:
    description: Can use /chess time
    default: op
  gregchess.chess.uci:
    description: Can use /chess uci
    default: op
  gregchess.chess.spectate:
    description: Can use /chess spectate
    default: true
  gregchess.chess.reload:
    description: Can use /chess reload
    default: op
  gregchess.chess.undo:
    description: Can use /chess undo
    default: true
  gregchess.chess.serial:
    description: Can use /chess serial
    default: op
  gregchess.chess.info.*:
    description: Can always use /chess info
    default: op
    children:
      gregchess.chess.info.remote: true
      gregchess.chess.info.ingame: true
  gregchess.chess.info.remote:
    description: Can use /chess info with uuids
    default: op
  gregchess.chess.info.ingame:
    description: Can use /chess info in-game
    default: op
  gregchess.chess.admin:
    description: Can use /chess admin
    default: op
  gregchess.chess.stats.*:
    description: Can fully use /chess stats
    default: op
    children:
      gregchess.chess.stats.read: true
      gregchess.chess.stats.set: true
  gregchess.chess.stats.self:
    description: Can use /chess stats
    default: true
  gregchess.chess.stats.read:
    description: Can use /chess stats with players
    default: true
    children:
      gregchess.chess.stats.self: true
  gregchess.chess.stats.set:
    description: Can use /chess stats set and clear
    default: op

